---
name: deployment-promote
on:
  schedule:
    - cron: '04 04 * * *'
env:
  TERM: dumb
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
jobs:
  promote:
    runs-on: ubuntu-24.04
    container: ghcr.io/menny/android_base:1.21.2
    strategy:
      matrix:
        # Not to interested in deploying addons. Disabling for now.
        #refname: [main, release-branch-addons-v5.0-r1]
        refname: [main]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ matrix.refname }}
      - name: request-scheduled-promote
        uses: ./.github/actions/deploy-request
        with:
          sha: HEAD
          ref: ${{ matrix.refname }}
          new_deploy: false
          api_username: ${{ secrets.BOT_MASTER_RW_GITHUB_USERNAME }}
          api_token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
          deployment_environment: ${{ github.event.deployment.environment }}
